#!/usr/bin/env -S npx tsx
/**
 * GENERATED BY PORTICO — do not edit by hand.
 *
 * Re-generate by compiling the target again from the Portico console (npm run dev).
 *
 * Every tool below was discovered by exploring a live web app that has no API.
 * Calling one costs a page load, not an agent session.
 */
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runTool } from "../app/_lib/driver/run";
import type { ToolSpec } from "../app/_lib/types";

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(await readFile(join(here, "tools.json"), "utf8")) as {
  target: string;
  tools: ToolSpec[];
};

const creds = {
  username: process.env.PORTICO_USERNAME ?? "Admin",
  password: process.env.PORTICO_PASSWORD ?? "admin123",
};

const server = new Server(
  { name: "portico-opensource-demo-orangehrmlive-com", version: "1.0.0" },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: manifest.tools.map((t) => ({
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  })),
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const tool = manifest.tools.find((t) => t.name === request.params.name);
  if (!tool) {
    return {
      isError: true,
      content: [{ type: "text", text: "Unknown tool: " + request.params.name }],
    };
  }

  try {
    const args = (request.params.arguments ?? {}) as Record<string, string>;
    const text = await runTool(manifest.target, creds, tool, args);
    return { content: [{ type: "text", text }] };
  } catch (err) {
    // Surface the failure: a silently empty result would look like "no records".
    return {
      isError: true,
      content: [{ type: "text", text: tool.name + " failed: " + (err as Error).message }],
    };
  }
});

await server.connect(new StdioServerTransport());
