import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import type { Credentials, ToolSpec } from "../types";

/**
 * Stage 5: write out a standalone MCP server.
 *
 * The emitted server embeds the compiled tools and calls the same deterministic
 * Playwright runtime the UI uses. It contains no model calls — that is the whole
 * point of compiling: discovery happened once, execution is now just a script.
 */

const SERVER_SOURCE = `#!/usr/bin/env -S npx tsx
/**
 * GENERATED BY PORTICO — do not edit by hand.
 *
 * Re-generate by compiling the target again from the Portico console (npm run dev).
 *
 * Every tool below was discovered by exploring a live web app that has no API.
 * Calling one costs a page load, not an agent session.
 */
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { runTool } from "../app/_lib/driver/run";
import type { ToolSpec } from "../app/_lib/types";

const here = dirname(fileURLToPath(import.meta.url));
const manifest = JSON.parse(await readFile(join(here, "tools.json"), "utf8")) as {
  target: string;
  tools: ToolSpec[];
};

const creds = {
  username: process.env.PORTICO_USERNAME ?? "__USERNAME__",
  password: process.env.PORTICO_PASSWORD ?? "__PASSWORD__",
};

const server = new Server(
  { name: "portico-__SLUG__", version: "1.0.0" },
  { capabilities: { tools: {} } },
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: manifest.tools.map((t) => ({
    name: t.name,
    description: t.description,
    inputSchema: t.inputSchema,
  })),
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const tool = manifest.tools.find((t) => t.name === request.params.name);
  if (!tool) {
    return {
      isError: true,
      content: [{ type: "text", text: "Unknown tool: " + request.params.name }],
    };
  }

  try {
    const args = (request.params.arguments ?? {}) as Record<string, string>;
    const text = await runTool(manifest.target, creds, tool, args);
    return { content: [{ type: "text", text }] };
  } catch (err) {
    // Surface the failure: a silently empty result would look like "no records".
    return {
      isError: true,
      content: [{ type: "text", text: tool.name + " failed: " + (err as Error).message }],
    };
  }
});

await server.connect(new StdioServerTransport());
`;

export type EmitResult = { dir: string; serverPath: string; toolCount: number };

export async function emitMcpServer(
  target: string,
  slug: string,
  tools: ToolSpec[],
  creds: Credentials,
): Promise<EmitResult> {
  const dir = join(process.cwd(), "mcp-server");
  await mkdir(dir, { recursive: true });

  const source = SERVER_SOURCE.replace("__SLUG__", slug)
    .replace("__USERNAME__", creds.username)
    .replace("__PASSWORD__", creds.password);

  const serverPath = join(dir, "server.mts");
  await writeFile(serverPath, source, "utf8");
  await writeFile(join(dir, "tools.json"), JSON.stringify({ target, tools }, null, 2), "utf8");

  // The exact command a user pastes to attach this to an agent.
  await writeFile(
    join(dir, "claude_mcp_config.json"),
    JSON.stringify(
      {
        mcpServers: {
          [`portico-${slug}`]: {
            command: "npx",
            args: ["tsx", serverPath],
          },
        },
      },
      null,
      2,
    ),
    "utf8",
  );

  return { dir, serverPath, toolCount: tools.length };
}
